/* Generated by version-info.py at configure time -- do not edit.
 * Feeds the 100-byte FirmwareIAPObj.Description blob the GCS parses
 * ("OpFw" layout, see devicedescriptorstruct.h): the uavo hash at offset
 * 60 is what the version-mismatch check actually compares. */
#pragma once
#include <stdint.h>

#define FW_VERSION_HASH32   0x${HASH8}u
#define FW_VERSION_UNIXTIME ${UNIXTIME}u
#define FW_VERSION_FWTAG    "${FWTAG}"
static const uint8_t fw_version_uavo_sha1[20] = { ${UAVO_HASH_ARRAY} };
